/**
 * This class is generated by jOOQ
 */
package model.mapping.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recipe implements Serializable {

	private static final long serialVersionUID = -57649520;

	private Integer recipeId;
	private String  dishName;
	private String  summary;
	private String  serving;
	private String  dishImageUrl;
	private Integer userId;

	public Recipe() {}

	public Recipe(Recipe value) {
		this.recipeId = value.recipeId;
		this.dishName = value.dishName;
		this.summary = value.summary;
		this.serving = value.serving;
		this.dishImageUrl = value.dishImageUrl;
		this.userId = value.userId;
	}

	public Recipe(
		Integer recipeId,
		String  dishName,
		String  summary,
		String  serving,
		String  dishImageUrl,
		Integer userId
	) {
		this.recipeId = recipeId;
		this.dishName = dishName;
		this.summary = summary;
		this.serving = serving;
		this.dishImageUrl = dishImageUrl;
		this.userId = userId;
	}

	public Integer getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(Integer recipeId) {
		this.recipeId = recipeId;
	}

	public String getDishName() {
		return this.dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getServing() {
		return this.serving;
	}

	public void setServing(String serving) {
		this.serving = serving;
	}

	public String getDishImageUrl() {
		return this.dishImageUrl;
	}

	public void setDishImageUrl(String dishImageUrl) {
		this.dishImageUrl = dishImageUrl;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Recipe (");

		sb.append(recipeId);
		sb.append(", ").append(dishName);
		sb.append(", ").append(summary);
		sb.append(", ").append(serving);
		sb.append(", ").append(dishImageUrl);
		sb.append(", ").append(userId);

		sb.append(")");
		return sb.toString();
	}
}
